# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/mainwindow.ui',
# licensing of 'gui/ui/mainwindow.ui' applies.
#
# Created: Sun May  9 11:28:34 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1322, 769)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Predict = QtWidgets.QWidget()
        self.Predict.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Predict.sizePolicy().hasHeightForWidth())
        self.Predict.setSizePolicy(sizePolicy)
        self.Predict.setObjectName("Predict")
        self.gridLayout = QtWidgets.QGridLayout(self.Predict)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Predict)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(850, 120))
        self.groupBox_3.setMaximumSize(QtCore.QSize(0, 120))
        self.groupBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.modelList = QtWidgets.QComboBox(self.groupBox_3)
        self.modelList.setMaximumSize(QtCore.QSize(100, 25))
        self.modelList.setObjectName("modelList")
        self.modelList.addItem("")
        self.modelList.addItem("")
        self.modelList.addItem("")
        self.modelList.addItem("")
        self.modelList.addItem("")
        self.modelList.addItem("")
        self.horizontalLayout.addWidget(self.modelList)
        self.predictButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predictButton.sizePolicy().hasHeightForWidth())
        self.predictButton.setSizePolicy(sizePolicy)
        self.predictButton.setObjectName("predictButton")
        self.horizontalLayout.addWidget(self.predictButton)
        self.gridLayout.addWidget(self.groupBox_3, 4, 0, 1, 1)
        self.picView = QtWidgets.QLabel(self.Predict)
        self.picView.setAutoFillBackground(True)
        self.picView.setText("")
        self.picView.setObjectName("picView")
        self.gridLayout.addWidget(self.picView, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.Predict)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.lblPredict = QtWidgets.QLabel(self.groupBox)
        self.lblPredict.setText("")
        self.lblPredict.setObjectName("lblPredict")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lblPredict)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 1)
        self.lblFilename = QtWidgets.QLabel(self.Predict)
        self.lblFilename.setMinimumSize(QtCore.QSize(0, 0))
        self.lblFilename.setMaximumSize(QtCore.QSize(16777215, 18))
        self.lblFilename.setObjectName("lblFilename")
        self.gridLayout.addWidget(self.lblFilename, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Predict, "")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.browseFilesButton = QtWidgets.QPushButton(self.groupBox_4)
        self.browseFilesButton.setObjectName("browseFilesButton")
        self.gridLayout_5.addWidget(self.browseFilesButton, 1, 0, 1, 1)
        self.fileList = QtWidgets.QListWidget(self.groupBox_4)
        self.fileList.setObjectName("fileList")
        self.gridLayout_5.addWidget(self.fileList, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.txtOutput = QtWidgets.QTextBrowser(self.groupBox_2)
        self.txtOutput.setObjectName("txtOutput")
        self.gridLayout_4.addWidget(self.txtOutput, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1322, 27))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Model Options", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Model", None, -1))
        self.modelList.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Inception", None, -1))
        self.modelList.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Resnet", None, -1))
        self.modelList.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "VGG", None, -1))
        self.modelList.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "myCNN", None, -1))
        self.modelList.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "Xception", None, -1))
        self.modelList.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "Densenet", None, -1))
        self.predictButton.setText(QtWidgets.QApplication.translate("MainWindow", "Predict", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Prediction", None, -1))
        self.lblFilename.setText(QtWidgets.QApplication.translate("MainWindow", "Selected Image: ", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Predict), QtWidgets.QApplication.translate("MainWindow", "Predict", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "File(s)", None, -1))
        self.browseFilesButton.setText(QtWidgets.QApplication.translate("MainWindow", "Browse Files", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Server Output", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))

